#!/bin/sh


# This script change the npm url registry to the current git branch.
# If you want to be update with npm module you must `npm install`.  

#TODO: need to config to the current address & port
serverUrl='http://localhost:4873/'



#init branchName & urlNpmName
branchName=`git rev-parse --abbrev-ref HEAD`
urlNpmName=`npm get registry`
constBranch="-branch"

#On Master branch the name module without name brnach. keep be minimal.
if [ ! "$branchName" == "master" ]; then
	
#standardization Branch Name
# replace all slash (/)  with dash (-)
branchName="${branchName////-}"

#Concat brnach name & "brnach-" const to the URL
newUrlNpm=${serverUrl}${branchName}${constBranch}

else
	newUrlNpm=${serverUrl}
fi

#set npm registry
`npm set registry ${newUrlNpm}`



echo ""
echo "Set npm registry url: ${newUrlNpm}"
echo "Note: remember to do npm install if you want that a npm module will be update to the current branch" 
echo "Mce Hook Checkout is Done!" 
